[package]
name = "builder"
version = "0.1.0"
edition = "2024"

authors = ["Adolfo GÃ³mez <dkmaster@dkmon.com>"]
license = "BSD-3-Clause"

[lib]
path = "src/lib.rs"

[dependencies]
chrono = "0.4.42"
winres = "0.1.12"