[package]
name = "launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
tokio = { version = "1.48.0", features = ["rt"] }

eframe = { version = "0.33.2" }
image = { version = "0.25.8", features = ["png"] }
open = "5.3.2"

[build-dependencies]
builder = { path = "../builder" }
