[package]
name = "launcher"
version = "5.0.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
js = { path = "../js" }
gui = { path = "../gui" }
rdp = { path = "../rdp/rdp" }


anyhow = "1.0.100"

tokio = { version = "1.48.0", features = ["rt"] }

eframe = { version = "0.33.2" }
image = { version = "0.25.8", features = ["png"] }
open = "5.3.2"

# Persistence
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

# i18n
gettext = "0.4.0"
rust-embed = "8.9.0"
sys-locale = "0.3.2"

crossbeam = "0.8"

[build-dependencies]
builder = { path = "../builder" }
