[package]
name = "gui"
version = "5.0.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
rdp = { path = "../rdp/rdp" }

anyhow = "1.0"

crossbeam = "0.8"
tokio = { version = "1.48.0", features = ["sync"] }

eframe = { version = "0.33.2" }
winit = "0.30.12"

zeroize = { version = "1", features = ["derive"] }
image = { version = "0.25.8", features = ["png"] }

# For opening links
open = "5.3.3"

gettext = "0.4.0"