[package]
name = "gui"
version = "5.0.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
connection = { path = "../connection" }
rdp = { path = "../rdp/rdp" }

anyhow = { workspace = true }

crossbeam = { workspace = true }
tokio = { workspace = true }

eframe = { workspace = true }
winit = { workspace = true }

zeroize = { workspace = true }
image = { workspace = true }

open = { workspace = true }

gettext = { workspace = true }
