[package]
name = "gui"
version = "5.0.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
rdp = { path = "../rdp/rdp" }

anyhow = { workspace = true }

crossbeam = { workspace = true }
tokio = { workspace = true }

eframe = { workspace = true }
winit = "0.30.12"

zeroize = { workspace = true }
image = { workspace = true }

# For opening links
open = "5.3"

gettext = { workspace = true }
