[workspace]
members = [
    "crates/builder",
    "crates/launcher",
    "crates/mac-launcher",
    "crates/shared",
    "crates/mldsa-verify",
    "crates/script-tester",
    "crates/gui",
    "crates/rdp/rdp",
    "crates/rdp/freerdp-sys", "crates/gui-tester",
]
resolver = "3"

[workspace.metadata.clippy]
skip = ["crates/rdp/rdp/freerdp-sys"]
