[workspace]
members = [
    "crates/builder",
    "crates/launcher",
    "crates/mac-launcher",
    "crates/shared",
    "crates/mldsa-verify",
    "crates/script-tester",
    "crates/gui",
    "crates/rdp/rdp",
    "crates/rdp/freerdp-sys",
    "crates/gui-tester",
    "crates/js",
    "crates/audio",
]
resolver = "3"

[workspace.dependencies]
# Utilities
anyhow = "1.0"
zeroize = { version = "1", features = ["derive"] }

# Concurrency channels and utilities
crossbeam = "0.8.4"

# SSL/TLS
rustls = "0.23.35"
rustls-native-certs = "0.8.2"

# async & async TLS
tokio-rustls = "0.26.4"
tokio = { version = "1.48", features = [
    "net",
    "io-util",
    "rt",
    "sync",
    "macros",
    "time",
    "process",
] }
futures = "0.3.31"
async-trait = "0.1.89"

# Json handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Encoding/Decoding
base64 = "0.22.1"
bzip2 = "0.6.1"

# Multilingual support
gettext = "0.4.0"

# Graphics/UI
eframe = { version = "0.33.2", features = ["glow"] }
image = { version = "0.25.8", features = ["png"] }

# Windows
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_System_Registry",
    "Win32_Security_Cryptography",
    "Win32_System_JobObjects",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Networking_WinSock",
] }
widestring = { version = "1.2" }
