[package]
name = "js"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }

# JavaScript engine
boa_engine = { version = "0.21.0" }

# Serialization
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

tokio = { version = "1.48.0", features = ["macros", "process"] }
futures = "0.3.31"
async-trait = "0.1.89"
regex = "1.12.2"

anyhow = "1.0.100"
rand = "0.9.2"

# For checking if a file is executable
is_executable = "1.0.5"

[dev-dependencies]
base64 = "0.22.1"
