[package]
name = "rdp"
version = "5.0.0"
edition = "2024"

[dependencies]
freerdp-sys = { path = "../freerdp-sys" }
shared = { path = "../../shared" }
audio = { path = "../../audio" }

anyhow = { workspace = true }

crossbeam = { workspace = true }

# Security dependencies
zeroize = { workspace = true }

# Clipboard dependencies
clipboard-rs = { workspace = true }

# Windows dependencies
[target.'cfg(windows)'.dependencies]
windows = { workspace = true }

[build-dependencies]
glob = { workspace = true }