[package]
name = "shared"
version = "5.0.0"
edition = "2024"

authors = ["Adolfo GÃ³mez <dkmaster@dkmon.com>"]
license = "BSD-3-Clause"

[dependencies]

# Logging
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = [
    "env-filter",
    "local-time",
] }
tracing-log = "0.2.0"

anyhow = { workspace = true }
chrono = { version = "0.4.42" }
directories-next = "2.0.0"

hostname = "0.4.2"

# Encoding/Decoding
base64 = { workspace = true }
bzip2 = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

rand = "0.9.2"

# SSL/TLS
rustls = { workspace = true }
rustls-native-certs = { workspace = true }

# non blocking TLS streams
tokio-rustls = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }

# HTTP client
reqwest = { version = "0.12.24", features = [
    "json",
    "rustls-tls",
    "system-proxy",
] }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }
widestring = { workspace = true }

# On a separate crate due to the dependency on the ML DSA crate
# which is not needed elsewhere
[dependencies.mldsa-verify]
path = "../mldsa-verify"

[dev-dependencies]
rcgen = "0.14.5"
serial_test = "3.2.0"
mockito = "1.7.1"
