[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
# Logging
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = [
    "env-filter",
    "local-time",
] }
tracing-log = "0.2.0"

anyhow = "1.0.100"
chrono = { version = "0.4.42" }

hostname = "0.4.1"

# JavaScript engine
boa_engine = "0.21.0"
# Tokio for boa async support
tokio = { version = "1.48.0", features = [
    "macros",
    "rt",
    "time",
    "sync",
    "signal",
] }
