[package]
name = "shared"
version = "0.1.0"
edition = "2024"

authors = ["Adolfo GÃ³mez <dkmaster@dkmon.com>"]
license = "BSD-3-Clause"

[dependencies]
# Logging
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = [
    "env-filter",
    "local-time",
] }
tracing-log = "0.2.0"

anyhow = "1.0.100"
chrono = { version = "0.4.42" }

hostname = "0.4.1"
regex = "1.12.2"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_System_Registry",
    "Win32_Security_Cryptography",
    "Win32_System_JobObjects",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }
widestring = "1.2.1"
base64 = "0.22.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

# JavaScript engine
boa_engine = "0.21.0"
# For checking if a file is executable
is_executable = "1.0.5"
rand = "0.9.2"

# SSL/TLS
rustls = "0.23.35"
rustls-native-certs = "0.8.2"
# non blocking TLS streams
tokio-rustls = "0.26.4"
tokio = { version = "1.48.0", features = [
    "net",
    "io-util",
    "rt",
    "sync",
    "macros",
    "time",
] }
futures = "0.3.31"

[dev-dependencies]
rcgen = "0.14.5"
